spring:
  application:
    name: api-gateway
  lifecycle:
    timeout-per-shutdown-phase: 20s
  cloud:
    gateway:
      mvc:
        routes:
          - id: Bank-ms
            uri: lb://BANK-MS
            predicates:
              - Path=/clients/**
          - id: IaModel-ms
            uri: lb://IAMODEL-MS
            predicates:
              - Path=/app/**
          - id: Eligibility-ms
            uri: lb://ELIGIBILITY-MS
            predicates:
              - Path=/eligibility/**


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/e-banking
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 9004
  shutdown: graceful

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-server-discovery.onrender.com/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    hostname: apigateway-a3y7.onrender.com
    preferIpAddress: false
    securePortEnabled: true
    nonSecurePortEnabled: false
    securePort: 443
    instanceId: ${spring.application.name}:${random.uuid}
    statusPageUrl: https://${eureka.instance.hostname}/actuator/info
    healthCheckUrl: https://${eureka.instance.hostname}/actuator/health
    homePageUrl: https://${eureka.instance.hostname}/
    metadataMap:
      instanceId: ${spring.application.name}:${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

jwt:
  auth:
    converter:
      resource-id: e-banking-rest-api
      principle-attribute: preferred_username

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: e-banking
  resource: backend-client
  public-client: false
  credentials:
    secret: QBafFQGFvlGsvttMMBX7Qa6urFrr7RsG
  bearer-only: true

cors:
  allowed:
    origin: http://localhost:5173