spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: Bank-ms
            uri: lb://BANK-MS
            predicates:
              - Path=/clients/**
          - id: IaModel-ms
            uri: lb://IAMODEL-MS
            predicates:
              - Path=/app/**
          - id: Eligibility-ms
            uri: lb://ELIGIBILITY-MS
            predicates:
              - Path=/eligibility/**

  security:
    oauth2:
      resourceserver:
        jwt:
          # Remplacez avec l'URL de production de Keycloak
          issuer-uri: ${KEYCLOAK_URL}/realms/e-banking
          jwk-set-uri: ${KEYCLOAK_URL}/realms/e-banking/protocol/openid-connect/certs

server:
  port: ${PORT:9004}

eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: https://eureka-server-discovery.onrender.com/eureka/
    webclient:
      enabled: true
  instance:
    hostname: apigateway-a3y7.onrender.com
    instanceId: ${eureka.instance.hostname}:${spring.application.name}:${random.value}
    securePort: 443
    securePortEnabled: true
    nonSecurePortEnabled: false
    preferIpAddress: false
    statusPageUrl: https://${eureka.instance.hostname}/actuator/info
    healthCheckUrl: https://${eureka.instance.hostname}/actuator/health
    homePageUrl: https://${eureka.instance.hostname}/

jwt:
  auth:
    converter:
      resource-id: e-banking-rest-api
      principle-attribute: preferred_username

keycloak:
  # Remplacez avec l'URL de production de Keycloak
  auth-server-url: ${KEYCLOAK_URL}
  realm: e-banking
  resource: backend-client
  public-client: false
  credentials:
    secret: ${KEYCLOAK_SECRET}
  bearer-only: true

cors:
  allowed:
    # Ajoutez votre URL frontend de production
    origin: ${CORS_ALLOWED_ORIGIN}