spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: Bank-ms
            uri: lb://BANK-MS
            predicates:
              - Path=/clients/**
          - id: IaModel-ms
            uri: lb://IAMODEL-MS
            predicates:
              - Path=/app/**
          - id: Eligibility-ms
            uri: lb://ELIGIBILITY-MS
            predicates:
              - Path=/eligibility/**


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/e-banking
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 9004
eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: https://eureka-server-discovery.onrender.com/eureka/
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    hostname: ${GATEWAY_HOST:https://apigateway-a3y7.onrender.com}
    non-secure-port: 80
    secure-port: 443
    non-secure-port-enabled: false
    secure-port-enabled: true
    prefer-ip-address: false

jwt:
  auth:
    converter:
      resource-id: e-banking-rest-api
      principle-attribute: preferred_username

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: e-banking
  resource: backend-client
  public-client: false
  credentials:
    secret: QBafFQGFvlGsvttMMBX7Qa6urFrr7RsG
  bearer-only: true

cors:
  allowed:
    origin: http://localhost:5173